// MBTI interpretation library. Pure data + composition. No AI, no network.

export type MbtiProfile = {
  type: string;
  nickname: string;
  core: string;
  strengths: string[];
  blindSpots: string[];
  communication: string;
  decisions: string;
  stress: string;
  relationships: string;
  work: string;
};

export const MBTI_AXES = [
  { key: "EI", left: "E", right: "I", leftName: "Extraversion", rightName: "Introversion" },
  { key: "SN", left: "S", right: "N", leftName: "Sensing", rightName: "Intuition" },
  { key: "TF", left: "T", right: "F", leftName: "Thinking", rightName: "Feeling" },
  { key: "JP", left: "J", right: "P", leftName: "Judging", rightName: "Perceiving" },
] as const;

export const LETTER_NOTE: Record<string, string> = {
  E: "attention moves outward; thinking happens partly out loud",
  I: "attention moves inward; processing happens before speaking",
  S: "trusts concrete detail, precedent and direct observation",
  N: "trusts pattern, inference and what something could become",
  T: "weighs coherence and consequence first",
  F: "weighs impact on people and values first",
  J: "prefers decisions closed and structure settled",
  P: "prefers options open and structure emergent",
};

const T = (
  type: string,
  nickname: string,
  core: string,
  strengths: string[],
  blindSpots: string[],
  communication: string,
  decisions: string,
  stress: string,
  relationships: string,
  work: string,
): MbtiProfile => ({
  type,
  nickname,
  core,
  strengths,
  blindSpots,
  communication,
  decisions,
  stress,
  relationships,
  work,
});

export const MBTI_LIBRARY: Record<string, MbtiProfile> = Object.fromEntries(
  [
    T(
      "INTJ",
      "The Architect",
      "You run a long internal model of how things work and move only when the model holds.",
      ["Strategic foresight", "Independent judgement", "Ruthless prioritisation"],
      ["Dismissing input that arrives unstructured", "Treating feelings as data errors", "Deciding privately, then announcing"],
      "Compressed and conclusion-first: you tend to hand over the answer and leave the reasoning implicit, which can read as cold when it is actually efficient.",
      "You decide slowly then commit hard, and you dislike reopening a question you consider settled.",
      "Under pressure you retreat into planning, over-control detail, and can turn unusually blunt.",
      "You show love through logistics and loyalty rather than continuous emotional narration, and you need a partner who does not read quiet as absence.",
      "You do best owning a domain end to end with few status meetings and a long enough horizon to be right.",
    ),
    T(
      "INTP",
      "The Analyst",
      "You take ideas apart for the pleasure of seeing the mechanism, and you resist conclusions that outrun the evidence.",
      ["Conceptual precision", "Intellectual honesty", "Comfort with ambiguity"],
      ["Endless refinement instead of shipping", "Withdrawing from emotional logistics", "Debating the frame when a decision is needed"],
      "Exploratory and qualified: you think in caveats, which is accurate but can sound like reluctance to commit.",
      "You keep options open until the last responsible moment and dislike being forced into false certainty.",
      "Under stress you disappear into abstraction, sleep and schedule go first, and irritation leaks out sideways.",
      "You attach deeply but quietly, and you need conversational range more than constant contact.",
      "You need autonomy, unstructured thinking time and problems that are genuinely unsolved.",
    ),
    T(
      "ENTJ",
      "The Commander",
      "You organise reality around objectives and find inefficiency almost physically uncomfortable.",
      ["Decisiveness under uncertainty", "Systems thinking at scale", "Willingness to be unpopular"],
      ["Steamrolling quieter input", "Impatience read as contempt", "Underweighting morale as a real variable"],
      "Direct, fast, load-bearing: you say the thing, and you expect the same back rather than diplomatic packaging.",
      "You decide quickly on partial information and course-correct in motion.",
      "Stress makes you escalate control and work, and vulnerability arrives late and abruptly.",
      "You express care by building things for people, and you need a partner who can hold their own ground without a fight becoming existential.",
      "You thrive with authority, measurable outcomes and permission to restructure what is broken.",
    ),
    T(
      "ENTP",
      "The Challenger of Premises",
      "You test ideas by pressure, generating options faster than most people can evaluate them.",
      ["Rapid ideation", "Reframing stuck problems", "Persuasive improvisation"],
      ["Arguing for sport past the point of use", "Abandoning projects at 80 percent", "Novelty crowding out follow-through"],
      "Playful, associative, provocative: you often argue a position to find its edges, not because you hold it.",
      "You prefer to keep decisions reversible and treat commitment as an option cost.",
      "Under stress you scatter, chase new stimulus, and can become uncharacteristically cutting.",
      "You need mental spark as a condition of attraction, and you can mistake calm for boredom.",
      "You perform best early in ventures, at the framing and prototyping stage, with someone else on operations.",
    ),
    T(
      "INFJ",
      "The Advocate",
      "You read undercurrents early and carry a private vision of how things ought to be.",
      ["Pattern-reading of people", "Sustained conviction", "Depth of insight"],
      ["Absorbing others' states as your own", "Idealising then abruptly withdrawing", "Naming problems late, when they are already large"],
      "Careful and layered: you say the kind version first and the whole version only when trust is established.",
      "You weigh values heavily and can override your own needs to preserve harmony.",
      "Stress collapses you inward; when it overloads, you become uncharacteristically rigid or self-critical.",
      "You want depth quickly and few relationships rather than many, and door-slam withdrawal is your protective reflex.",
      "You need meaning as a non-negotiable and quiet conditions to produce your best work.",
    ),
    T(
      "INFP",
      "The Idealist",
      "You navigate by an internal value compass that is quiet but almost immovable.",
      ["Moral clarity", "Imaginative empathy", "Authenticity under pressure"],
      ["Conflict avoidance until resentment builds", "Deferring structure until it becomes urgent", "Comparing your inner ideal to your visible output"],
      "Gentle, indirect, metaphor-friendly: you feel far more than you initially say.",
      "You decide by what feels right against your values and resist purely tactical logic.",
      "Under stress you turn self-critical, then unusually harsh or blaming in ways that surprise you afterwards.",
      "You love idealistically and hate to disappoint, so you may over-adapt before you state a need.",
      "You need work aligned with something you believe in and freedom from close supervision.",
    ),
    T(
      "ENFJ",
      "The Protagonist",
      "You organise people toward a shared good and feel responsible for the emotional weather.",
      ["Reading and mobilising groups", "Warm, articulate influence", "Genuine developmental instinct"],
      ["Over-functioning for others", "Managing perception instead of stating need", "Resentment when care is not reciprocated"],
      "Encouraging and fluent: you name what people are feeling before they do, which can occasionally overwrite them.",
      "You decide with values plus consequence for the group, sometimes discounting your own preference.",
      "Stress shows as over-giving, then burnout and unusually pointed criticism.",
      "You give generously and need explicit appreciation more than you like to admit.",
      "You do well where relationships and outcomes intersect: leadership, teaching, coordination, advocacy.",
    ),
    T(
      "ENFP",
      "The Catalyst",
      "You move through possibility and people with unusual warmth and momentum.",
      ["Contagious enthusiasm", "Fast rapport", "Seeing potential in people and projects"],
      ["Overcommitting", "Losing interest at the maintenance stage", "Avoiding hard conversations to protect connection"],
      "Expansive and emotionally present: you talk in possibilities and connections, sometimes several at once.",
      "You decide on resonance and momentum, then rationalise afterwards.",
      "Under stress you fragment, over-plan trivia, and can spiral into pessimism that is out of character.",
      "You fall in fast and need both freedom and reassurance, which can look contradictory from outside.",
      "You thrive in varied, people-facing, creative work with minimal routine.",
    ),
    T(
      "ISTJ",
      "The Steward",
      "You keep your word and keep the system running when nobody is watching.",
      ["Reliability", "Precision with detail", "Institutional memory"],
      ["Resisting change with sound reasons", "Under-expressing appreciation", "Absorbing load silently until it is unfair"],
      "Plain, sequential, evidence-based: you dislike hyperbole and prefer verifiable statements.",
      "You decide from precedent and demonstrated fact, and dislike improvising on incomplete data.",
      "Stress makes you double down on procedure and grow quietly critical.",
      "You show love through consistency and provision rather than declaration.",
      "You do best with clear standards, defined scope and low chaos.",
    ),
    T(
      "ISFJ",
      "The Guardian",
      "You notice what people need and quietly hold the practical fabric of their lives together.",
      ["Attentive care", "Steady follow-through", "Excellent memory for people"],
      ["Difficulty saying no", "Storing hurt rather than voicing it", "Undervaluing your own contribution"],
      "Warm and understated: you soften delivery and often ask questions instead of asserting.",
      "You decide with loyalty and duty weighted heavily, sometimes at your own cost.",
      "Under stress you over-serve, then become uncharacteristically catastrophic in outlook.",
      "You are steadfast and need to feel specifically valued, not just relied upon.",
      "You excel where care, continuity and reliability matter more than novelty.",
    ),
    T(
      "ESTJ",
      "The Organiser",
      "You bring order and accountability wherever you land, quickly.",
      ["Operational competence", "Clear standards", "Decisive execution"],
      ["Assuming your structure is the only structure", "Bluntness landing harder than intended", "Impatience with processing time"],
      "Explicit and directive: expectations, deadlines and consequences stated plainly.",
      "You decide fast on established logic and dislike revisiting settled matters.",
      "Stress increases control, volume and micromanagement.",
      "You are dependable and demonstrative through action, and you need respect as much as affection.",
      "You are strongest managing people, processes and delivery against clear metrics.",
    ),
    T(
      "ESFJ",
      "The Host",
      "You build belonging and keep the social system warm and functioning.",
      ["Practical generosity", "Social attunement", "Follow-through on commitments"],
      ["Over-reliance on approval", "Conflict smoothed rather than resolved", "Taking disagreement personally"],
      "Warm, personal, inclusive: you check how things land as you go.",
      "You decide with people's feelings and shared norms front and centre.",
      "Under stress you over-give, then feel unappreciated and can become critical.",
      "You love actively and attentively and need reciprocity to feel secure.",
      "You shine in roles built on relationships, coordination and service.",
    ),
    T(
      "ISTP",
      "The Troubleshooter",
      "You understand things by handling them, and you stay calm exactly where others panic.",
      ["Composure in crisis", "Mechanical and practical intelligence", "Economy of effort"],
      ["Emotional under-disclosure", "Disengaging instead of negotiating", "Boredom with maintenance and ceremony"],
      "Minimal and factual: you say what is needed and consider the rest noise.",
      "You decide in the moment with the situation in front of you rather than the plan on paper.",
      "Stress makes you go quiet and physically absent before you go verbal.",
      "You show care through competence and presence, and you need real independence inside closeness.",
      "You do best with hands-on autonomy, live problems and minimal bureaucracy.",
    ),
    T(
      "ISFP",
      "The Composer",
      "You live by direct aesthetic and moral feel, and you rarely explain it.",
      ["Sensory and aesthetic acuity", "Quiet integrity", "Present-moment attention"],
      ["Avoiding confrontation", "Deferring planning", "Withdrawing when criticised"],
      "Soft, concrete, understated: you show rather than argue.",
      "You decide from values and immediate feel, not from abstraction.",
      "Under stress you retreat and turn self-critical, sometimes uncharacteristically sharp.",
      "You express love in tangible, sensory, private ways and dislike performance.",
      "You need creative autonomy, aesthetic quality and freedom from rigid procedure.",
    ),
    T(
      "ESTP",
      "The Operator",
      "You read the room and the situation fast and act while others are still deliberating.",
      ["Real-time decisiveness", "Persuasive presence", "High tolerance for risk"],
      ["Impulse over consequence", "Under-processing emotional signal", "Restlessness in slow environments"],
      "Punchy, concrete, confident: you negotiate live rather than in writing.",
      "You decide on immediate feedback and adjust as you go.",
      "Stress pushes you into action, stimulation or avoidance rather than reflection.",
      "You pursue with energy and need excitement, and you can mistake stability for stagnation.",
      "You thrive in fast, competitive, tangible work with visible results.",
    ),
    T(
      "ESFP",
      "The Performer",
      "You bring warmth, immediacy and life to whatever room you are in.",
      ["Emotional generosity", "Adaptability", "Ability to lift a group instantly"],
      ["Avoiding heavy topics", "Short planning horizon", "Seeking novelty when feelings get uncomfortable"],
      "Expressive and physical: tone and presence carry more than the words.",
      "You decide with feeling and momentum in the present.",
      "Under stress you distract, socialise, or spiral into unusually dark rumination.",
      "You love demonstratively and need affection and shared experience to feel secure.",
      "You do best in vivid, people-rich, varied work with quick feedback.",
    ),
  ].map((p) => [p.type, p]),
);

export function mbtiDimensionText(type: string): string[] {
  return type.split("").map((letter) => `${letter} — ${LETTER_NOTE[letter] ?? ""}`);
}
