/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InputRouteImport } from './routes/input'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AssessmentKindRouteImport } from './routes/assessment.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentKindRoute = AssessmentKindRouteImport.update({
  id: '/assessment/$kind',
  path: '/assessment/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/input': typeof InputRoute
  '/report': typeof ReportRoute
  '/assessment/$kind': typeof AssessmentKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/input': typeof InputRoute
  '/report': typeof ReportRoute
  '/assessment/$kind': typeof AssessmentKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/input': typeof InputRoute
  '/report': typeof ReportRoute
  '/assessment/$kind': typeof AssessmentKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/input' | '/report' | '/assessment/$kind'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/input' | '/report' | '/assessment/$kind'
  id: '__root__' | '/' | '/input' | '/report' | '/assessment/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InputRoute: typeof InputRoute
  ReportRoute: typeof ReportRoute
  AssessmentKindRoute: typeof AssessmentKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$kind': {
      id: '/assessment/$kind'
      path: '/assessment/$kind'
      fullPath: '/assessment/$kind'
      preLoaderRoute: typeof AssessmentKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InputRoute: InputRoute,
  ReportRoute: ReportRoute,
  AssessmentKindRoute: AssessmentKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
